version: '3.8'

services:
  postgres:
    container_name: product-pg
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: product
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  product:
    build: .
    ports:
      - 3333:3333
    environment:
      - PORT=3333
      - DATABASE_URL=postgresql://postgres:docker@postgres:5432/product?schema=public
      - JWT_PRIVATE_KEY=PRIVATE_KEY_IN_BASE64
      - JWT_PUBLIC_KEY=PUBLIC_KEY_IN_BASE64